# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:year/:month/:day/:title.html
relative_permalinks: true

# Setup
title:               'Santiago Basulto | Blog'
tagline:             ''
description:         ''
url:                 http://blog.santiagobasulto.com.ar
baseurl:             /
paginate:            5

# About/contact
author:
  name:              'Santiago Basulto'
  url:               https://twitter.com/santiagobasulto
  email:             santiago.basulto@gmail.com

# Custom vars
version:             1.0.0
